# Generated by Django 4.1.7 on 2023-05-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='product/'),
        ),
    ]
