# Generated by Django 4.1.7 on 2023-05-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(default='True', max_length=60)),
                ('quan', models.CharField(default='True', max_length=60)),
                ('price', models.CharField(default='True', max_length=60)),
            ],
        ),
    ]
