# Generated by Django 4.1.7 on 2023-06-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_crud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
