# Generated by Django 4.1.7 on 2023-06-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_crud',
            old_name='product_image',
            new_name='pro_img',
        ),
        migrations.RenameField(
            model_name='product_crud',
            old_name='name',
            new_name='pro_name',
        ),
    ]
